package com.kung.dppf.entity.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kung.dppf.entity.ProductBean;
import com.kung.dppf.entity.ProductNutrition;
import com.kung.dppf.entity.ProductType;
import com.kung.dppf.entity.WeighRecord;

import com.kung.dppf.entity.greendao.ProductBeanDao;
import com.kung.dppf.entity.greendao.ProductNutritionDao;
import com.kung.dppf.entity.greendao.ProductTypeDao;
import com.kung.dppf.entity.greendao.WeighRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productBeanDaoConfig;
    private final DaoConfig productNutritionDaoConfig;
    private final DaoConfig productTypeDaoConfig;
    private final DaoConfig weighRecordDaoConfig;

    private final ProductBeanDao productBeanDao;
    private final ProductNutritionDao productNutritionDao;
    private final ProductTypeDao productTypeDao;
    private final WeighRecordDao weighRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productBeanDaoConfig = daoConfigMap.get(ProductBeanDao.class).clone();
        productBeanDaoConfig.initIdentityScope(type);

        productNutritionDaoConfig = daoConfigMap.get(ProductNutritionDao.class).clone();
        productNutritionDaoConfig.initIdentityScope(type);

        productTypeDaoConfig = daoConfigMap.get(ProductTypeDao.class).clone();
        productTypeDaoConfig.initIdentityScope(type);

        weighRecordDaoConfig = daoConfigMap.get(WeighRecordDao.class).clone();
        weighRecordDaoConfig.initIdentityScope(type);

        productBeanDao = new ProductBeanDao(productBeanDaoConfig, this);
        productNutritionDao = new ProductNutritionDao(productNutritionDaoConfig, this);
        productTypeDao = new ProductTypeDao(productTypeDaoConfig, this);
        weighRecordDao = new WeighRecordDao(weighRecordDaoConfig, this);

        registerDao(ProductBean.class, productBeanDao);
        registerDao(ProductNutrition.class, productNutritionDao);
        registerDao(ProductType.class, productTypeDao);
        registerDao(WeighRecord.class, weighRecordDao);
    }
    
    public void clear() {
        productBeanDaoConfig.clearIdentityScope();
        productNutritionDaoConfig.clearIdentityScope();
        productTypeDaoConfig.clearIdentityScope();
        weighRecordDaoConfig.clearIdentityScope();
    }

    public ProductBeanDao getProductBeanDao() {
        return productBeanDao;
    }

    public ProductNutritionDao getProductNutritionDao() {
        return productNutritionDao;
    }

    public ProductTypeDao getProductTypeDao() {
        return productTypeDao;
    }

    public WeighRecordDao getWeighRecordDao() {
        return weighRecordDao;
    }

}
