package com.kung.dppf.entity.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kung.dppf.entity.ProductBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCT_BEAN".
*/
public class ProductBeanDao extends AbstractDao<ProductBean, Long> {

    public static final String TABLENAME = "PRODUCT_BEAN";

    /**
     * Properties of entity ProductBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property ProductCode = new Property(1, String.class, "ProductCode", false, "PRODUCT_CODE");
        public final static Property ProductName = new Property(2, String.class, "ProductName", false, "PRODUCT_NAME");
        public final static Property TypeName = new Property(3, String.class, "TypeName", false, "TYPE_NAME");
        public final static Property IngredientContent = new Property(4, String.class, "IngredientContent", false, "INGREDIENT_CONTENT");
        public final static Property ShelfLife = new Property(5, String.class, "ShelfLife", false, "SHELF_LIFE");
        public final static Property StorageMethod = new Property(6, String.class, "StorageMethod", false, "STORAGE_METHOD");
        public final static Property EdibleMethod = new Property(7, String.class, "EdibleMethod", false, "EDIBLE_METHOD");
        public final static Property Precautions = new Property(8, String.class, "Precautions", false, "PRECAUTIONS");
        public final static Property Standard = new Property(9, String.class, "Standard", false, "STANDARD");
        public final static Property ProductionLicense = new Property(10, String.class, "ProductionLicense", false, "PRODUCTION_LICENSE");
        public final static Property Manufacturer = new Property(11, String.class, "Manufacturer", false, "MANUFACTURER");
        public final static Property Address = new Property(12, String.class, "Address", false, "ADDRESS");
        public final static Property Entrust = new Property(13, String.class, "Entrust", false, "ENTRUST");
        public final static Property EntrustAddress = new Property(14, String.class, "EntrustAddress", false, "ENTRUST_ADDRESS");
        public final static Property Origin = new Property(15, String.class, "Origin", false, "ORIGIN");
        public final static Property Phone = new Property(16, String.class, "Phone", false, "PHONE");
        public final static Property UpdateTime = new Property(17, String.class, "updateTime", false, "UPDATE_TIME");
    }


    public ProductBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ProductBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"PRODUCT_CODE\" TEXT UNIQUE ," + // 1: ProductCode
                "\"PRODUCT_NAME\" TEXT," + // 2: ProductName
                "\"TYPE_NAME\" TEXT," + // 3: TypeName
                "\"INGREDIENT_CONTENT\" TEXT," + // 4: IngredientContent
                "\"SHELF_LIFE\" TEXT," + // 5: ShelfLife
                "\"STORAGE_METHOD\" TEXT," + // 6: StorageMethod
                "\"EDIBLE_METHOD\" TEXT," + // 7: EdibleMethod
                "\"PRECAUTIONS\" TEXT," + // 8: Precautions
                "\"STANDARD\" TEXT," + // 9: Standard
                "\"PRODUCTION_LICENSE\" TEXT," + // 10: ProductionLicense
                "\"MANUFACTURER\" TEXT," + // 11: Manufacturer
                "\"ADDRESS\" TEXT," + // 12: Address
                "\"ENTRUST\" TEXT," + // 13: Entrust
                "\"ENTRUST_ADDRESS\" TEXT," + // 14: EntrustAddress
                "\"ORIGIN\" TEXT," + // 15: Origin
                "\"PHONE\" TEXT," + // 16: Phone
                "\"UPDATE_TIME\" TEXT);"); // 17: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProductBean entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String ProductCode = entity.getProductCode();
        if (ProductCode != null) {
            stmt.bindString(2, ProductCode);
        }
 
        String ProductName = entity.getProductName();
        if (ProductName != null) {
            stmt.bindString(3, ProductName);
        }
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(4, TypeName);
        }
 
        String IngredientContent = entity.getIngredientContent();
        if (IngredientContent != null) {
            stmt.bindString(5, IngredientContent);
        }
 
        String ShelfLife = entity.getShelfLife();
        if (ShelfLife != null) {
            stmt.bindString(6, ShelfLife);
        }
 
        String StorageMethod = entity.getStorageMethod();
        if (StorageMethod != null) {
            stmt.bindString(7, StorageMethod);
        }
 
        String EdibleMethod = entity.getEdibleMethod();
        if (EdibleMethod != null) {
            stmt.bindString(8, EdibleMethod);
        }
 
        String Precautions = entity.getPrecautions();
        if (Precautions != null) {
            stmt.bindString(9, Precautions);
        }
 
        String Standard = entity.getStandard();
        if (Standard != null) {
            stmt.bindString(10, Standard);
        }
 
        String ProductionLicense = entity.getProductionLicense();
        if (ProductionLicense != null) {
            stmt.bindString(11, ProductionLicense);
        }
 
        String Manufacturer = entity.getManufacturer();
        if (Manufacturer != null) {
            stmt.bindString(12, Manufacturer);
        }
 
        String Address = entity.getAddress();
        if (Address != null) {
            stmt.bindString(13, Address);
        }
 
        String Entrust = entity.getEntrust();
        if (Entrust != null) {
            stmt.bindString(14, Entrust);
        }
 
        String EntrustAddress = entity.getEntrustAddress();
        if (EntrustAddress != null) {
            stmt.bindString(15, EntrustAddress);
        }
 
        String Origin = entity.getOrigin();
        if (Origin != null) {
            stmt.bindString(16, Origin);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(17, Phone);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(18, updateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProductBean entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String ProductCode = entity.getProductCode();
        if (ProductCode != null) {
            stmt.bindString(2, ProductCode);
        }
 
        String ProductName = entity.getProductName();
        if (ProductName != null) {
            stmt.bindString(3, ProductName);
        }
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(4, TypeName);
        }
 
        String IngredientContent = entity.getIngredientContent();
        if (IngredientContent != null) {
            stmt.bindString(5, IngredientContent);
        }
 
        String ShelfLife = entity.getShelfLife();
        if (ShelfLife != null) {
            stmt.bindString(6, ShelfLife);
        }
 
        String StorageMethod = entity.getStorageMethod();
        if (StorageMethod != null) {
            stmt.bindString(7, StorageMethod);
        }
 
        String EdibleMethod = entity.getEdibleMethod();
        if (EdibleMethod != null) {
            stmt.bindString(8, EdibleMethod);
        }
 
        String Precautions = entity.getPrecautions();
        if (Precautions != null) {
            stmt.bindString(9, Precautions);
        }
 
        String Standard = entity.getStandard();
        if (Standard != null) {
            stmt.bindString(10, Standard);
        }
 
        String ProductionLicense = entity.getProductionLicense();
        if (ProductionLicense != null) {
            stmt.bindString(11, ProductionLicense);
        }
 
        String Manufacturer = entity.getManufacturer();
        if (Manufacturer != null) {
            stmt.bindString(12, Manufacturer);
        }
 
        String Address = entity.getAddress();
        if (Address != null) {
            stmt.bindString(13, Address);
        }
 
        String Entrust = entity.getEntrust();
        if (Entrust != null) {
            stmt.bindString(14, Entrust);
        }
 
        String EntrustAddress = entity.getEntrustAddress();
        if (EntrustAddress != null) {
            stmt.bindString(15, EntrustAddress);
        }
 
        String Origin = entity.getOrigin();
        if (Origin != null) {
            stmt.bindString(16, Origin);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(17, Phone);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(18, updateTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ProductBean readEntity(Cursor cursor, int offset) {
        ProductBean entity = new ProductBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ProductCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ProductName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // TypeName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // IngredientContent
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ShelfLife
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // StorageMethod
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // EdibleMethod
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // Precautions
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // Standard
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ProductionLicense
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // Manufacturer
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // Address
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // Entrust
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // EntrustAddress
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // Origin
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // Phone
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17) // updateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProductBean entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProductName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTypeName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIngredientContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setShelfLife(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStorageMethod(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEdibleMethod(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPrecautions(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setStandard(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setProductionLicense(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setManufacturer(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAddress(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setEntrust(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setEntrustAddress(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setOrigin(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setPhone(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setUpdateTime(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProductBean entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProductBean entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProductBean entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
