package com.kung.dppf.entity.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kung.dppf.entity.ProductNutrition;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCT_NUTRITION".
*/
public class ProductNutritionDao extends AbstractDao<ProductNutrition, Long> {

    public static final String TABLENAME = "PRODUCT_NUTRITION";

    /**
     * Properties of entity ProductNutrition.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property ProductCode = new Property(1, String.class, "productCode", false, "PRODUCT_CODE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property Nrv = new Property(4, String.class, "nrv", false, "NRV");
        public final static Property Sort = new Property(5, int.class, "sort", false, "SORT");
    }


    public ProductNutritionDao(DaoConfig config) {
        super(config);
    }
    
    public ProductNutritionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCT_NUTRITION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"PRODUCT_CODE\" TEXT," + // 1: productCode
                "\"NAME\" TEXT," + // 2: name
                "\"CONTENT\" TEXT," + // 3: content
                "\"NRV\" TEXT," + // 4: nrv
                "\"SORT\" INTEGER NOT NULL );"); // 5: sort
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCT_NUTRITION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProductNutrition entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String productCode = entity.getProductCode();
        if (productCode != null) {
            stmt.bindString(2, productCode);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String nrv = entity.getNrv();
        if (nrv != null) {
            stmt.bindString(5, nrv);
        }
        stmt.bindLong(6, entity.getSort());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProductNutrition entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String productCode = entity.getProductCode();
        if (productCode != null) {
            stmt.bindString(2, productCode);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String nrv = entity.getNrv();
        if (nrv != null) {
            stmt.bindString(5, nrv);
        }
        stmt.bindLong(6, entity.getSort());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ProductNutrition readEntity(Cursor cursor, int offset) {
        ProductNutrition entity = new ProductNutrition( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // productCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // content
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // nrv
            cursor.getInt(offset + 5) // sort
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProductNutrition entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setContent(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNrv(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSort(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProductNutrition entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProductNutrition entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProductNutrition entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
