package com.kung.dppf.entity.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kung.dppf.entity.WeighRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEIGH_RECORD".
*/
public class WeighRecordDao extends AbstractDao<WeighRecord, Long> {

    public static final String TABLENAME = "WEIGH_RECORD";

    /**
     * Properties of entity WeighRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property ProductCode = new Property(1, String.class, "ProductCode", false, "PRODUCT_CODE");
        public final static Property ProductName = new Property(2, String.class, "ProductName", false, "PRODUCT_NAME");
        public final static Property TypeCode = new Property(3, String.class, "TypeCode", false, "TYPE_CODE");
        public final static Property TypeName = new Property(4, String.class, "TypeName", false, "TYPE_NAME");
        public final static Property IngredientContent = new Property(5, String.class, "IngredientContent", false, "INGREDIENT_CONTENT");
        public final static Property ShelfLife = new Property(6, String.class, "ShelfLife", false, "SHELF_LIFE");
        public final static Property StorageMethod = new Property(7, String.class, "StorageMethod", false, "STORAGE_METHOD");
        public final static Property EdibleMethod = new Property(8, String.class, "EdibleMethod", false, "EDIBLE_METHOD");
        public final static Property Precautions = new Property(9, String.class, "Precautions", false, "PRECAUTIONS");
        public final static Property Standard = new Property(10, String.class, "Standard", false, "STANDARD");
        public final static Property ProductionLicense = new Property(11, String.class, "ProductionLicense", false, "PRODUCTION_LICENSE");
        public final static Property Manufacturer = new Property(12, String.class, "Manufacturer", false, "MANUFACTURER");
        public final static Property Address = new Property(13, String.class, "Address", false, "ADDRESS");
        public final static Property Entrust = new Property(14, String.class, "Entrust", false, "ENTRUST");
        public final static Property EntrustAddress = new Property(15, String.class, "EntrustAddress", false, "ENTRUST_ADDRESS");
        public final static Property Origin = new Property(16, String.class, "Origin", false, "ORIGIN");
        public final static Property Phone = new Property(17, String.class, "Phone", false, "PHONE");
        public final static Property NutritionContent = new Property(18, String.class, "NutritionContent", false, "NUTRITION_CONTENT");
        public final static Property NetWeight = new Property(19, String.class, "NetWeight", false, "NET_WEIGHT");
        public final static Property ProductionDate = new Property(20, String.class, "ProductionDate", false, "PRODUCTION_DATE");
        public final static Property CreateTime = new Property(21, String.class, "createTime", false, "CREATE_TIME");
    }


    public WeighRecordDao(DaoConfig config) {
        super(config);
    }
    
    public WeighRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEIGH_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"PRODUCT_CODE\" TEXT," + // 1: ProductCode
                "\"PRODUCT_NAME\" TEXT," + // 2: ProductName
                "\"TYPE_CODE\" TEXT," + // 3: TypeCode
                "\"TYPE_NAME\" TEXT," + // 4: TypeName
                "\"INGREDIENT_CONTENT\" TEXT," + // 5: IngredientContent
                "\"SHELF_LIFE\" TEXT," + // 6: ShelfLife
                "\"STORAGE_METHOD\" TEXT," + // 7: StorageMethod
                "\"EDIBLE_METHOD\" TEXT," + // 8: EdibleMethod
                "\"PRECAUTIONS\" TEXT," + // 9: Precautions
                "\"STANDARD\" TEXT," + // 10: Standard
                "\"PRODUCTION_LICENSE\" TEXT," + // 11: ProductionLicense
                "\"MANUFACTURER\" TEXT," + // 12: Manufacturer
                "\"ADDRESS\" TEXT," + // 13: Address
                "\"ENTRUST\" TEXT," + // 14: Entrust
                "\"ENTRUST_ADDRESS\" TEXT," + // 15: EntrustAddress
                "\"ORIGIN\" TEXT," + // 16: Origin
                "\"PHONE\" TEXT," + // 17: Phone
                "\"NUTRITION_CONTENT\" TEXT," + // 18: NutritionContent
                "\"NET_WEIGHT\" TEXT," + // 19: NetWeight
                "\"PRODUCTION_DATE\" TEXT," + // 20: ProductionDate
                "\"CREATE_TIME\" TEXT);"); // 21: createTime
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_WEIGH_RECORD_PRODUCT_NAME ON \"WEIGH_RECORD\"" +
                " (\"PRODUCT_NAME\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_WEIGH_RECORD_TYPE_NAME ON \"WEIGH_RECORD\"" +
                " (\"TYPE_NAME\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_WEIGH_RECORD_CREATE_TIME ON \"WEIGH_RECORD\"" +
                " (\"CREATE_TIME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEIGH_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WeighRecord entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String ProductCode = entity.getProductCode();
        if (ProductCode != null) {
            stmt.bindString(2, ProductCode);
        }
 
        String ProductName = entity.getProductName();
        if (ProductName != null) {
            stmt.bindString(3, ProductName);
        }
 
        String TypeCode = entity.getTypeCode();
        if (TypeCode != null) {
            stmt.bindString(4, TypeCode);
        }
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(5, TypeName);
        }
 
        String IngredientContent = entity.getIngredientContent();
        if (IngredientContent != null) {
            stmt.bindString(6, IngredientContent);
        }
 
        String ShelfLife = entity.getShelfLife();
        if (ShelfLife != null) {
            stmt.bindString(7, ShelfLife);
        }
 
        String StorageMethod = entity.getStorageMethod();
        if (StorageMethod != null) {
            stmt.bindString(8, StorageMethod);
        }
 
        String EdibleMethod = entity.getEdibleMethod();
        if (EdibleMethod != null) {
            stmt.bindString(9, EdibleMethod);
        }
 
        String Precautions = entity.getPrecautions();
        if (Precautions != null) {
            stmt.bindString(10, Precautions);
        }
 
        String Standard = entity.getStandard();
        if (Standard != null) {
            stmt.bindString(11, Standard);
        }
 
        String ProductionLicense = entity.getProductionLicense();
        if (ProductionLicense != null) {
            stmt.bindString(12, ProductionLicense);
        }
 
        String Manufacturer = entity.getManufacturer();
        if (Manufacturer != null) {
            stmt.bindString(13, Manufacturer);
        }
 
        String Address = entity.getAddress();
        if (Address != null) {
            stmt.bindString(14, Address);
        }
 
        String Entrust = entity.getEntrust();
        if (Entrust != null) {
            stmt.bindString(15, Entrust);
        }
 
        String EntrustAddress = entity.getEntrustAddress();
        if (EntrustAddress != null) {
            stmt.bindString(16, EntrustAddress);
        }
 
        String Origin = entity.getOrigin();
        if (Origin != null) {
            stmt.bindString(17, Origin);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(18, Phone);
        }
 
        String NutritionContent = entity.getNutritionContent();
        if (NutritionContent != null) {
            stmt.bindString(19, NutritionContent);
        }
 
        String NetWeight = entity.getNetWeight();
        if (NetWeight != null) {
            stmt.bindString(20, NetWeight);
        }
 
        String ProductionDate = entity.getProductionDate();
        if (ProductionDate != null) {
            stmt.bindString(21, ProductionDate);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(22, createTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WeighRecord entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String ProductCode = entity.getProductCode();
        if (ProductCode != null) {
            stmt.bindString(2, ProductCode);
        }
 
        String ProductName = entity.getProductName();
        if (ProductName != null) {
            stmt.bindString(3, ProductName);
        }
 
        String TypeCode = entity.getTypeCode();
        if (TypeCode != null) {
            stmt.bindString(4, TypeCode);
        }
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(5, TypeName);
        }
 
        String IngredientContent = entity.getIngredientContent();
        if (IngredientContent != null) {
            stmt.bindString(6, IngredientContent);
        }
 
        String ShelfLife = entity.getShelfLife();
        if (ShelfLife != null) {
            stmt.bindString(7, ShelfLife);
        }
 
        String StorageMethod = entity.getStorageMethod();
        if (StorageMethod != null) {
            stmt.bindString(8, StorageMethod);
        }
 
        String EdibleMethod = entity.getEdibleMethod();
        if (EdibleMethod != null) {
            stmt.bindString(9, EdibleMethod);
        }
 
        String Precautions = entity.getPrecautions();
        if (Precautions != null) {
            stmt.bindString(10, Precautions);
        }
 
        String Standard = entity.getStandard();
        if (Standard != null) {
            stmt.bindString(11, Standard);
        }
 
        String ProductionLicense = entity.getProductionLicense();
        if (ProductionLicense != null) {
            stmt.bindString(12, ProductionLicense);
        }
 
        String Manufacturer = entity.getManufacturer();
        if (Manufacturer != null) {
            stmt.bindString(13, Manufacturer);
        }
 
        String Address = entity.getAddress();
        if (Address != null) {
            stmt.bindString(14, Address);
        }
 
        String Entrust = entity.getEntrust();
        if (Entrust != null) {
            stmt.bindString(15, Entrust);
        }
 
        String EntrustAddress = entity.getEntrustAddress();
        if (EntrustAddress != null) {
            stmt.bindString(16, EntrustAddress);
        }
 
        String Origin = entity.getOrigin();
        if (Origin != null) {
            stmt.bindString(17, Origin);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(18, Phone);
        }
 
        String NutritionContent = entity.getNutritionContent();
        if (NutritionContent != null) {
            stmt.bindString(19, NutritionContent);
        }
 
        String NetWeight = entity.getNetWeight();
        if (NetWeight != null) {
            stmt.bindString(20, NetWeight);
        }
 
        String ProductionDate = entity.getProductionDate();
        if (ProductionDate != null) {
            stmt.bindString(21, ProductionDate);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(22, createTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WeighRecord readEntity(Cursor cursor, int offset) {
        WeighRecord entity = new WeighRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ProductCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ProductName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // TypeCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // TypeName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // IngredientContent
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ShelfLife
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // StorageMethod
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // EdibleMethod
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // Precautions
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // Standard
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // ProductionLicense
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // Manufacturer
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // Address
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // Entrust
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // EntrustAddress
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // Origin
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // Phone
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // NutritionContent
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // NetWeight
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // ProductionDate
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21) // createTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WeighRecord entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProductName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTypeCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTypeName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIngredientContent(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setShelfLife(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStorageMethod(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEdibleMethod(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPrecautions(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setStandard(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setProductionLicense(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setManufacturer(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setAddress(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setEntrust(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setEntrustAddress(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setOrigin(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPhone(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setNutritionContent(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setNetWeight(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setProductionDate(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setCreateTime(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WeighRecord entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WeighRecord entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WeighRecord entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
